// Generated by scripts/gen_parallel_schedule.py. Do not edit by hand.
package ldpc_schedule_pkg;
    localparam int SCHEDULE_MAX_LANES = 16;
    localparam int SCHEDULE_SUPPORTED_COUNT = 3;

    function automatic bit schedule_lanes_supported(input int unsigned lanes);
        case (lanes)
            1, 8, 16: schedule_lanes_supported = 1'b1;
            default: schedule_lanes_supported = 1'b0;
        endcase
    endfunction

    function automatic int unsigned schedule_group_count(input int unsigned lanes);
        case (lanes)
            1: schedule_group_count = 1536;
            8: schedule_group_count = 192;
            16: schedule_group_count = 96;
            default: schedule_group_count = 0;
        endcase
    endfunction

    function automatic bit schedule_row_valid(
        input int unsigned lanes,
        input int unsigned group_idx,
        input int unsigned lane_idx
    );
        schedule_row_valid =
            schedule_lanes_supported(lanes) &&
            (lane_idx < lanes) &&
            (group_idx < schedule_group_count(lanes));
    endfunction

    function automatic int unsigned schedule_row_index(
        input int unsigned lanes,
        input int unsigned group_idx,
        input int unsigned lane_idx
    );
        schedule_row_index = (group_idx * lanes) + lane_idx;
    endfunction

    function automatic int unsigned schedule_row_degree(input int unsigned row_idx);
        if (row_idx < 512) begin
            schedule_row_degree = 3;
        end else begin
            schedule_row_degree = 6;
        end
    endfunction

    function automatic int unsigned schedule_posterior_bank(
        input int unsigned lanes,
        input int unsigned variable_idx
    );
        schedule_posterior_bank = variable_idx % lanes;
    endfunction

    function automatic int unsigned schedule_posterior_addr(
        input int unsigned lanes,
        input int unsigned variable_idx
    );
        schedule_posterior_addr = variable_idx / lanes;
    endfunction

    function automatic int unsigned schedule_message_bank(input int unsigned lane_idx);
        schedule_message_bank = lane_idx;
    endfunction

    function automatic int unsigned schedule_message_addr(input int unsigned group_idx);
        schedule_message_addr = group_idx;
    endfunction
endpackage
