#!/usr/bin/env python3
"""Generate deterministic parallel LDPC schedule artifacts."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from models import ar4ja_matrix as ar4ja
from models.ldpc_schedule import SUPPORTED_LANES, build_schedule, schedule_report

DEFAULT_SV_OUTPUT = Path("rtl/ldpc_schedule_pkg.sv")
DEFAULT_REPORT_DIR = Path("vectors/schedule")


def generate_sv_package(output: Path = DEFAULT_SV_OUTPUT) -> Path:
    output.parent.mkdir(parents=True, exist_ok=True)
    text = f"""// Generated by scripts/gen_parallel_schedule.py. Do not edit by hand.
package ldpc_schedule_pkg;
    localparam int SCHEDULE_MAX_LANES = {max(SUPPORTED_LANES)};
    localparam int SCHEDULE_SUPPORTED_COUNT = {len(SUPPORTED_LANES)};

    function automatic bit schedule_lanes_supported(input int unsigned lanes);
        case (lanes)
            1, 8, 16: schedule_lanes_supported = 1'b1;
            default: schedule_lanes_supported = 1'b0;
        endcase
    endfunction

    function automatic int unsigned schedule_group_count(input int unsigned lanes);
        case (lanes)
            1: schedule_group_count = {ar4ja.CHECKS};
            8: schedule_group_count = {ar4ja.CHECKS // 8};
            16: schedule_group_count = {ar4ja.CHECKS // 16};
            default: schedule_group_count = 0;
        endcase
    endfunction

    function automatic bit schedule_row_valid(
        input int unsigned lanes,
        input int unsigned group_idx,
        input int unsigned lane_idx
    );
        schedule_row_valid =
            schedule_lanes_supported(lanes) &&
            (lane_idx < lanes) &&
            (group_idx < schedule_group_count(lanes));
    endfunction

    function automatic int unsigned schedule_row_index(
        input int unsigned lanes,
        input int unsigned group_idx,
        input int unsigned lane_idx
    );
        schedule_row_index = (group_idx * lanes) + lane_idx;
    endfunction

    function automatic int unsigned schedule_row_degree(input int unsigned row_idx);
        if (row_idx < {ar4ja.M}) begin
            schedule_row_degree = 3;
        end else begin
            schedule_row_degree = 6;
        end
    endfunction

    function automatic int unsigned schedule_posterior_bank(
        input int unsigned lanes,
        input int unsigned variable_idx
    );
        schedule_posterior_bank = variable_idx % lanes;
    endfunction

    function automatic int unsigned schedule_posterior_addr(
        input int unsigned lanes,
        input int unsigned variable_idx
    );
        schedule_posterior_addr = variable_idx / lanes;
    endfunction

    function automatic int unsigned schedule_message_bank(input int unsigned lane_idx);
        schedule_message_bank = lane_idx;
    endfunction

    function automatic int unsigned schedule_message_addr(input int unsigned group_idx);
        schedule_message_addr = group_idx;
    endfunction
endpackage
"""
    output.write_text(text, encoding="ascii")
    return output


def generate_reports(output_dir: Path = DEFAULT_REPORT_DIR) -> list[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    paths: list[Path] = []
    for lanes in SUPPORTED_LANES:
        schedule = build_schedule(lanes)
        path = output_dir / f"schedule_lanes_{lanes}.txt"
        path.write_text(schedule_report(schedule) + "\n", encoding="ascii")
        paths.append(path)
    return paths


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--sv-output", type=Path, default=DEFAULT_SV_OUTPUT)
    parser.add_argument("--report-dir", type=Path, default=DEFAULT_REPORT_DIR)
    args = parser.parse_args()

    sv_path = generate_sv_package(args.sv_output)
    report_paths = generate_reports(args.report_dir)
    print(f"wrote {sv_path}")
    for path in report_paths:
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
