#!/usr/bin/env python3
"""Generate deterministic syndrome-checker vectors."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from models import ar4ja_matrix as ar4ja
from models import ldpc_encoder

DEFAULT_OUTPUT_DIR = Path("vectors/syndrome")


def _bit_string(bits: np.ndarray) -> str:
    return "".join("1" if int(bit) else "0" for bit in bits)


def _hex_string_lsb_indexed(bits: np.ndarray) -> str:
    value = 0
    for index, bit in enumerate(bits):
        if int(bit):
            value |= 1 << index
    width = (len(bits) + 3) // 4
    return f"{value:0{width}x}"


def _payloads() -> list[tuple[str, np.ndarray]]:
    rng1 = np.random.default_rng(1)
    rng2 = np.random.default_rng(2)
    return [
        ("valid_zero", np.zeros(ar4ja.INFO_N, dtype=np.uint8)),
        ("valid_seed_1", rng1.integers(0, 2, ar4ja.INFO_N, dtype=np.uint8)),
        ("valid_seed_2", rng2.integers(0, 2, ar4ja.INFO_N, dtype=np.uint8)),
    ]


def generate_vectors(output_dir: Path = DEFAULT_OUTPUT_DIR) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    vector_path = output_dir / "syndrome_vectors.txt"
    tx_mem_path = output_dir / "tx.mem"
    syndrome_mem_path = output_dir / "syndrome.mem"
    pass_mem_path = output_dir / "pass.mem"
    meta_path = output_dir / "syndrome_meta.svh"

    rows: list[tuple[str, np.ndarray, np.ndarray, int]] = []
    for name, payload in _payloads():
        tx = ldpc_encoder.encode(payload)
        syndrome = ar4ja.syndrome_transmitted(tx, ar4ja.PUNCTURE_SOLVE)
        rows.append((name, tx, syndrome, 1))

        if name == "valid_seed_1":
            corrupt = tx.copy()
            corrupt[0] ^= 1
            rows.append(
                (
                    "corrupt_seed_1_bit_0",
                    corrupt,
                    ar4ja.syndrome_transmitted(corrupt, ar4ja.PUNCTURE_SOLVE),
                    0,
                )
            )

            corrupt = tx.copy()
            corrupt[ar4ja.TX_N - 1] ^= 1
            rows.append(
                (
                    "corrupt_seed_1_last_tx_bit",
                    corrupt,
                    ar4ja.syndrome_transmitted(corrupt, ar4ja.PUNCTURE_SOLVE),
                    0,
                )
            )

    with vector_path.open("w", encoding="ascii") as handle:
        handle.write("# name tx_bits syndrome_bits expected_pass\n")
        handle.write(f"# tx_bits length {ar4ja.TX_N}, syndrome_bits length {ar4ja.CHECKS}\n")
        handle.write(f"# puncture_policy {ar4ja.PUNCTURE_SOLVE}\n")
        for name, tx, syndrome, expected_pass in rows:
            handle.write(
                f"{name} {_bit_string(tx)} {_bit_string(syndrome)} {expected_pass}\n"
            )

    with tx_mem_path.open("w", encoding="ascii") as handle:
        for _, tx, _, _ in rows:
            handle.write(_hex_string_lsb_indexed(tx) + "\n")

    with syndrome_mem_path.open("w", encoding="ascii") as handle:
        for _, _, syndrome, _ in rows:
            handle.write(_hex_string_lsb_indexed(syndrome) + "\n")

    with pass_mem_path.open("w", encoding="ascii") as handle:
        for _, _, _, expected_pass in rows:
            handle.write(f"{expected_pass:b}\n")

    with meta_path.open("w", encoding="ascii") as handle:
        handle.write("// Generated by scripts/gen_vectors.py. Do not edit by hand.\n")
        handle.write(f"localparam int SYNDROME_VECTOR_COUNT = {len(rows)};\n")

    return vector_path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    args = parser.parse_args()
    path = generate_vectors(args.output_dir)
    print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
